
services:
  # Development overrides
  database:
    ports:
      - "3306:3306"
      
  app:
    ports:
      - "9000:9000"
    environment:
      XDEBUG_MODE: debug
      
  nginx:
    ports:
      - "8080:80"
      
  redis:
    ports:
      - "6379:6379"
