
services:
  # Development overrides
  database:
    ports:
      - "3306:3306"
      
  app:
    ports:
      - "9000:9000"
    environment:
      XDEBUG_MODE: debug
      
  nginx:
    ports:
      - "8080:80"
      
  redis:
    ports:
      - "6379:6379"
      
  # Development scheduler service
  scheduler:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/www/html
      - app_var:/var/www/html/var
    environment:
      DATABASE_URL: mysql://app:app_password@database:3306/crypto_exchange?serverVersion=8.0
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    command: bash -c "cd /var/www/html && bash scripts/start-scheduler.sh"
